language: objective-c
script:
  - xctool -project KTCSVParser.xcodeproj -scheme KTCSVParser -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -project KTCSVParser.xcodeproj -scheme KTCSVParserTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
